
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action QuitButton;

	private global::Gtk.Action RunButton;

	private global::Gtk.Action PauseButton;

	private global::Gtk.Action SaveButton;

	private global::Gtk.Action ClearButton;

	private global::Gtk.Action ShowButton;

	private global::Gtk.ToggleAction TurmiteAddButton;

	private global::Gtk.Action CopyProgramButton;

	private global::Gtk.Fixed MainLayout;

	private global::Gtk.Notebook MainNoteBook;

	private global::Gtk.Fixed pageWorldLayout;

	private global::Gtk.EventBox WorldEventBox;

	private global::Gtk.Image WorldImage;

	private global::Gtk.VScrollbar WorldImageScrollY;

	private global::Gtk.HScrollbar WorldImageScrollX;

	private global::Gtk.Label pageLabelWorld;

	private global::Gtk.Notebook PropertiesNotebook;

	private global::Gtk.Fixed PropertiesPageLayout;

	private global::Gtk.Label PropertiesPageWorldLabel;

	private global::Gtk.Label WorldLabelWidth;

	private global::Gtk.SpinButton WorldWidth;

	private global::Gtk.SpinButton WorldHeight;

	private global::Gtk.Label WorldLabelHeight;

	private global::Gtk.Label TurmitesLabel;

	private global::Gtk.ComboBox TurmitesList;

	private global::Gtk.Label TurmiteLabelHead;

	private global::Gtk.SpinButton TurmiteHeadX;

	private global::Gtk.SpinButton TurmiteHeadY;

	private global::Gtk.Label TurmiteLabelHeadX;

	private global::Gtk.Label TurmiteLabelHeadY;

	private global::Gtk.Label TurmiteLabelSource;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView TurmiteProgram;

	private global::Gtk.ColorButton TurmiteColor;

	private global::Gtk.Label TurmiteLabelColor;

	private global::Gtk.Toolbar TurmiteToolBar;

	private global::Gtk.CheckButton TL;

	private global::Gtk.Label LabelNeighborhood;

	private global::Gtk.CheckButton TM;

	private global::Gtk.CheckButton TR;

	private global::Gtk.CheckButton ML;

	private global::Gtk.Label LabelCenter;

	private global::Gtk.CheckButton MR;

	private global::Gtk.CheckButton BL;

	private global::Gtk.CheckButton BM;

	private global::Gtk.CheckButton BR;

	private global::Gtk.Label LabelStates;

	private global::Gtk.SpinButton TurmiteStates;

	private global::Gtk.ComboBox TurmiteLibrary;

	private global::Gtk.Label LabelTurmiteLibrary;

	private global::Gtk.Toolbar LibraryToolbar;

	private global::Gtk.Button AddButton;

	private global::Gtk.CheckButton Cyclic;

	private global::Gtk.Label PropertiesPageLabel;

	private global::Gtk.Toolbar MainToolbar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.QuitButton = new global::Gtk.Action("QuitButton", null, global::Mono.Unix.Catalog.GetString("Exit"), "gtk-quit");
		w1.Add(this.QuitButton, null);
		this.RunButton = new global::Gtk.Action("RunButton", null, global::Mono.Unix.Catalog.GetString("Run Simulation"), "gtk-media-play");
		w1.Add(this.RunButton, null);
		this.PauseButton = new global::Gtk.Action("PauseButton", null, global::Mono.Unix.Catalog.GetString("Stop Simulation"), "gtk-media-stop");
		w1.Add(this.PauseButton, null);
		this.SaveButton = new global::Gtk.Action("SaveButton", null, null, "gtk-save");
		w1.Add(this.SaveButton, null);
		this.ClearButton = new global::Gtk.Action("ClearButton", null, global::Mono.Unix.Catalog.GetString("Remove All Turmites"), "gtk-delete");
		w1.Add(this.ClearButton, null);
		this.ShowButton = new global::Gtk.Action("ShowButton", null, global::Mono.Unix.Catalog.GetString("Show/Hide Turmite Head Locations"), "gtk-find");
		w1.Add(this.ShowButton, null);
		this.TurmiteAddButton = new global::Gtk.ToggleAction("TurmiteAddButton", null, global::Mono.Unix.Catalog.GetString("Add Turmite"), "gtk-edit");
		this.TurmiteAddButton.DrawAsRadio = true;
		w1.Add(this.TurmiteAddButton, null);
		this.CopyProgramButton = new global::Gtk.Action("CopyProgramButton", null, global::Mono.Unix.Catalog.GetString("Copy Program"), "gtk-copy");
		w1.Add(this.CopyProgramButton, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("GTK Turmites");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("Turmites.dna.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 1280;
		this.DefaultHeight = 700;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainLayout = new global::Gtk.Fixed();
		this.MainLayout.WidthRequest = 1280;
		this.MainLayout.HeightRequest = 700;
		this.MainLayout.Name = "MainLayout";
		this.MainLayout.HasWindow = false;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.MainNoteBook = new global::Gtk.Notebook();
		this.MainNoteBook.WidthRequest = 800;
		this.MainNoteBook.HeightRequest = 600;
		this.MainNoteBook.CanFocus = true;
		this.MainNoteBook.Name = "MainNoteBook";
		this.MainNoteBook.CurrentPage = 0;
		// Container child MainNoteBook.Gtk.Notebook+NotebookChild
		this.pageWorldLayout = new global::Gtk.Fixed();
		this.pageWorldLayout.Name = "pageWorldLayout";
		this.pageWorldLayout.HasWindow = false;
		// Container child pageWorldLayout.Gtk.Fixed+FixedChild
		this.WorldEventBox = new global::Gtk.EventBox();
		this.WorldEventBox.WidthRequest = 640;
		this.WorldEventBox.HeightRequest = 480;
		this.WorldEventBox.Name = "WorldEventBox";
		// Container child WorldEventBox.Gtk.Container+ContainerChild
		this.WorldImage = new global::Gtk.Image();
		this.WorldImage.WidthRequest = 640;
		this.WorldImage.HeightRequest = 480;
		this.WorldImage.Name = "WorldImage";
		this.WorldEventBox.Add(this.WorldImage);
		this.pageWorldLayout.Add(this.WorldEventBox);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.pageWorldLayout[this.WorldEventBox]));
		w3.X = 80;
		w3.Y = 40;
		// Container child pageWorldLayout.Gtk.Fixed+FixedChild
		this.WorldImageScrollY = new global::Gtk.VScrollbar(null);
		this.WorldImageScrollY.HeightRequest = 480;
		this.WorldImageScrollY.Name = "WorldImageScrollY";
		this.WorldImageScrollY.Adjustment.Upper = 100D;
		this.WorldImageScrollY.Adjustment.PageIncrement = 10D;
		this.WorldImageScrollY.Adjustment.PageSize = 10D;
		this.WorldImageScrollY.Adjustment.StepIncrement = 1D;
		this.pageWorldLayout.Add(this.WorldImageScrollY);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.pageWorldLayout[this.WorldImageScrollY]));
		w4.X = 40;
		w4.Y = 40;
		// Container child pageWorldLayout.Gtk.Fixed+FixedChild
		this.WorldImageScrollX = new global::Gtk.HScrollbar(null);
		this.WorldImageScrollX.WidthRequest = 640;
		this.WorldImageScrollX.Name = "WorldImageScrollX";
		this.WorldImageScrollX.Adjustment.Upper = 100D;
		this.WorldImageScrollX.Adjustment.PageIncrement = 10D;
		this.WorldImageScrollX.Adjustment.PageSize = 10D;
		this.WorldImageScrollX.Adjustment.StepIncrement = 1D;
		this.pageWorldLayout.Add(this.WorldImageScrollX);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.pageWorldLayout[this.WorldImageScrollX]));
		w5.X = 80;
		w5.Y = 540;
		this.MainNoteBook.Add(this.pageWorldLayout);
		// Notebook tab
		this.pageLabelWorld = new global::Gtk.Label();
		this.pageLabelWorld.Name = "pageLabelWorld";
		this.pageLabelWorld.LabelProp = global::Mono.Unix.Catalog.GetString("World");
		this.MainNoteBook.SetTabLabel(this.pageWorldLayout, this.pageLabelWorld);
		this.pageLabelWorld.ShowAll();
		this.MainLayout.Add(this.MainNoteBook);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainNoteBook]));
		w7.X = 20;
		w7.Y = 60;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.PropertiesNotebook = new global::Gtk.Notebook();
		this.PropertiesNotebook.WidthRequest = 400;
		this.PropertiesNotebook.HeightRequest = 600;
		this.PropertiesNotebook.CanFocus = true;
		this.PropertiesNotebook.Name = "PropertiesNotebook";
		this.PropertiesNotebook.CurrentPage = 0;
		// Container child PropertiesNotebook.Gtk.Notebook+NotebookChild
		this.PropertiesPageLayout = new global::Gtk.Fixed();
		this.PropertiesPageLayout.WidthRequest = 60;
		this.PropertiesPageLayout.Name = "PropertiesPageLayout";
		this.PropertiesPageLayout.HasWindow = false;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.PropertiesPageWorldLabel = new global::Gtk.Label();
		this.PropertiesPageWorldLabel.Name = "PropertiesPageWorldLabel";
		this.PropertiesPageWorldLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>World</b>");
		this.PropertiesPageWorldLabel.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.PropertiesPageWorldLabel);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.PropertiesPageWorldLabel]));
		w8.X = 10;
		w8.Y = 10;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.WorldLabelWidth = new global::Gtk.Label();
		this.WorldLabelWidth.WidthRequest = 60;
		this.WorldLabelWidth.Name = "WorldLabelWidth";
		this.WorldLabelWidth.LabelProp = global::Mono.Unix.Catalog.GetString("Width");
		this.WorldLabelWidth.Justify = ((global::Gtk.Justification)(1));
		this.PropertiesPageLayout.Add(this.WorldLabelWidth);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.WorldLabelWidth]));
		w9.X = 10;
		w9.Y = 45;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.WorldWidth = new global::Gtk.SpinButton(640D, 10000D, 1D);
		this.WorldWidth.WidthRequest = 150;
		this.WorldWidth.CanFocus = true;
		this.WorldWidth.Name = "WorldWidth";
		this.WorldWidth.Adjustment.PageIncrement = 1D;
		this.WorldWidth.ClimbRate = 1D;
		this.WorldWidth.Numeric = true;
		this.PropertiesPageLayout.Add(this.WorldWidth);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.WorldWidth]));
		w10.X = 80;
		w10.Y = 40;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.WorldHeight = new global::Gtk.SpinButton(480D, 10000D, 1D);
		this.WorldHeight.WidthRequest = 150;
		this.WorldHeight.CanFocus = true;
		this.WorldHeight.Name = "WorldHeight";
		this.WorldHeight.Adjustment.PageIncrement = 1D;
		this.WorldHeight.ClimbRate = 1D;
		this.WorldHeight.Numeric = true;
		this.PropertiesPageLayout.Add(this.WorldHeight);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.WorldHeight]));
		w11.X = 80;
		w11.Y = 80;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.WorldLabelHeight = new global::Gtk.Label();
		this.WorldLabelHeight.WidthRequest = 60;
		this.WorldLabelHeight.Name = "WorldLabelHeight";
		this.WorldLabelHeight.LabelProp = global::Mono.Unix.Catalog.GetString("Height");
		this.WorldLabelHeight.Justify = ((global::Gtk.Justification)(1));
		this.PropertiesPageLayout.Add(this.WorldLabelHeight);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.WorldLabelHeight]));
		w12.X = 10;
		w12.Y = 85;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmitesLabel = new global::Gtk.Label();
		this.TurmitesLabel.Name = "TurmitesLabel";
		this.TurmitesLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Turmites</b>");
		this.TurmitesLabel.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.TurmitesLabel);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmitesLabel]));
		w13.X = 10;
		w13.Y = 120;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmitesList = global::Gtk.ComboBox.NewText();
		this.TurmitesList.WidthRequest = 220;
		this.TurmitesList.Name = "TurmitesList";
		this.PropertiesPageLayout.Add(this.TurmitesList);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmitesList]));
		w14.X = 13;
		w14.Y = 143;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteLabelHead = new global::Gtk.Label();
		this.TurmiteLabelHead.Name = "TurmiteLabelHead";
		this.TurmiteLabelHead.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Head</b>");
		this.TurmiteLabelHead.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.TurmiteLabelHead);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteLabelHead]));
		w15.X = 40;
		w15.Y = 180;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteHeadX = new global::Gtk.SpinButton(0D, 10000D, 1D);
		this.TurmiteHeadX.WidthRequest = 150;
		this.TurmiteHeadX.CanFocus = true;
		this.TurmiteHeadX.Name = "TurmiteHeadX";
		this.TurmiteHeadX.Adjustment.PageIncrement = 1D;
		this.TurmiteHeadX.ClimbRate = 1D;
		this.TurmiteHeadX.Numeric = true;
		this.PropertiesPageLayout.Add(this.TurmiteHeadX);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteHeadX]));
		w16.X = 80;
		w16.Y = 200;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteHeadY = new global::Gtk.SpinButton(0D, 10000D, 1D);
		this.TurmiteHeadY.WidthRequest = 150;
		this.TurmiteHeadY.CanFocus = true;
		this.TurmiteHeadY.Name = "TurmiteHeadY";
		this.TurmiteHeadY.Adjustment.PageIncrement = 1D;
		this.TurmiteHeadY.ClimbRate = 1D;
		this.TurmiteHeadY.Numeric = true;
		this.PropertiesPageLayout.Add(this.TurmiteHeadY);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteHeadY]));
		w17.X = 80;
		w17.Y = 240;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteLabelHeadX = new global::Gtk.Label();
		this.TurmiteLabelHeadX.WidthRequest = 20;
		this.TurmiteLabelHeadX.Name = "TurmiteLabelHeadX";
		this.TurmiteLabelHeadX.LabelProp = global::Mono.Unix.Catalog.GetString("X");
		this.TurmiteLabelHeadX.Justify = ((global::Gtk.Justification)(1));
		this.PropertiesPageLayout.Add(this.TurmiteLabelHeadX);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteLabelHeadX]));
		w18.X = 50;
		w18.Y = 205;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteLabelHeadY = new global::Gtk.Label();
		this.TurmiteLabelHeadY.WidthRequest = 20;
		this.TurmiteLabelHeadY.Name = "TurmiteLabelHeadY";
		this.TurmiteLabelHeadY.LabelProp = global::Mono.Unix.Catalog.GetString("Y");
		this.TurmiteLabelHeadY.Justify = ((global::Gtk.Justification)(1));
		this.PropertiesPageLayout.Add(this.TurmiteLabelHeadY);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteLabelHeadY]));
		w19.X = 50;
		w19.Y = 245;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteLabelSource = new global::Gtk.Label();
		this.TurmiteLabelSource.Name = "TurmiteLabelSource";
		this.TurmiteLabelSource.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Program</b>");
		this.TurmiteLabelSource.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.TurmiteLabelSource);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteLabelSource]));
		w20.X = 80;
		w20.Y = 280;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TurmiteProgram = new global::Gtk.TextView();
		this.TurmiteProgram.WidthRequest = 150;
		this.TurmiteProgram.HeightRequest = 110;
		this.TurmiteProgram.CanFocus = true;
		this.TurmiteProgram.Name = "TurmiteProgram";
		this.GtkScrolledWindow.Add(this.TurmiteProgram);
		this.PropertiesPageLayout.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.GtkScrolledWindow]));
		w22.X = 78;
		w22.Y = 308;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteColor = new global::Gtk.ColorButton();
		this.TurmiteColor.WidthRequest = 150;
		this.TurmiteColor.CanFocus = true;
		this.TurmiteColor.Events = ((global::Gdk.EventMask)(784));
		this.TurmiteColor.Name = "TurmiteColor";
		this.PropertiesPageLayout.Add(this.TurmiteColor);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteColor]));
		w23.X = 80;
		w23.Y = 440;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteLabelColor = new global::Gtk.Label();
		this.TurmiteLabelColor.WidthRequest = 50;
		this.TurmiteLabelColor.Name = "TurmiteLabelColor";
		this.TurmiteLabelColor.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Color</b>");
		this.TurmiteLabelColor.UseMarkup = true;
		this.TurmiteLabelColor.Justify = ((global::Gtk.Justification)(1));
		this.PropertiesPageLayout.Add(this.TurmiteLabelColor);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteLabelColor]));
		w24.X = 25;
		w24.Y = 448;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'TurmiteToolBar\'><toolitem name=\'TurmiteAddButton\' action=\'Turm" +
				"iteAddButton\'/></toolbar></ui>");
		this.TurmiteToolBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/TurmiteToolBar")));
		this.TurmiteToolBar.Name = "TurmiteToolBar";
		this.TurmiteToolBar.ShowArrow = false;
		this.PropertiesPageLayout.Add(this.TurmiteToolBar);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteToolBar]));
		w25.X = 240;
		w25.Y = 138;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TL = new global::Gtk.CheckButton();
		this.TL.Name = "TL";
		this.TL.Label = "";
		this.TL.DrawIndicator = true;
		this.TL.UseUnderline = true;
		this.TL.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.TL);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TL]));
		w26.X = 260;
		w26.Y = 302;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.LabelNeighborhood = new global::Gtk.Label();
		this.LabelNeighborhood.Name = "LabelNeighborhood";
		this.LabelNeighborhood.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Neighborhood</b>");
		this.LabelNeighborhood.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.LabelNeighborhood);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.LabelNeighborhood]));
		w27.X = 260;
		w27.Y = 280;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TM = new global::Gtk.CheckButton();
		this.TM.CanFocus = true;
		this.TM.Name = "TM";
		this.TM.Label = "";
		this.TM.DrawIndicator = true;
		this.TM.UseUnderline = true;
		this.TM.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.TM);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TM]));
		w28.X = 290;
		w28.Y = 302;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TR = new global::Gtk.CheckButton();
		this.TR.Name = "TR";
		this.TR.Label = "";
		this.TR.DrawIndicator = true;
		this.TR.UseUnderline = true;
		this.TR.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.TR);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TR]));
		w29.X = 320;
		w29.Y = 302;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.ML = new global::Gtk.CheckButton();
		this.ML.Name = "ML";
		this.ML.Label = "";
		this.ML.DrawIndicator = true;
		this.ML.UseUnderline = true;
		this.ML.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.ML);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.ML]));
		w30.X = 260;
		w30.Y = 332;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.LabelCenter = new global::Gtk.Label();
		this.LabelCenter.Name = "LabelCenter";
		this.LabelCenter.LabelProp = global::Mono.Unix.Catalog.GetString("<b>T</b>");
		this.LabelCenter.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.LabelCenter);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.LabelCenter]));
		w31.X = 295;
		w31.Y = 335;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.MR = new global::Gtk.CheckButton();
		this.MR.Name = "MR";
		this.MR.Label = "";
		this.MR.DrawIndicator = true;
		this.MR.UseUnderline = true;
		this.MR.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.MR);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.MR]));
		w32.X = 320;
		w32.Y = 332;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.BL = new global::Gtk.CheckButton();
		this.BL.Name = "BL";
		this.BL.Label = "";
		this.BL.DrawIndicator = true;
		this.BL.UseUnderline = true;
		this.BL.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.BL);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.BL]));
		w33.X = 260;
		w33.Y = 362;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.BM = new global::Gtk.CheckButton();
		this.BM.Name = "BM";
		this.BM.Label = "";
		this.BM.DrawIndicator = true;
		this.BM.UseUnderline = true;
		this.BM.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.BM);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.BM]));
		w34.X = 290;
		w34.Y = 362;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.BR = new global::Gtk.CheckButton();
		this.BR.Name = "BR";
		this.BR.Label = "";
		this.BR.DrawIndicator = true;
		this.BR.UseUnderline = true;
		this.BR.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.BR);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.BR]));
		w35.X = 320;
		w35.Y = 362;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.LabelStates = new global::Gtk.Label();
		this.LabelStates.Name = "LabelStates";
		this.LabelStates.LabelProp = global::Mono.Unix.Catalog.GetString("<b>States</b>");
		this.LabelStates.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.LabelStates);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.LabelStates]));
		w36.X = 260;
		w36.Y = 210;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteStates = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.TurmiteStates.WidthRequest = 100;
		this.TurmiteStates.CanFocus = true;
		this.TurmiteStates.Name = "TurmiteStates";
		this.TurmiteStates.Adjustment.PageIncrement = 1D;
		this.TurmiteStates.ClimbRate = 1D;
		this.TurmiteStates.Numeric = true;
		this.PropertiesPageLayout.Add(this.TurmiteStates);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteStates]));
		w37.X = 260;
		w37.Y = 240;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.TurmiteLibrary = global::Gtk.ComboBox.NewText();
		this.TurmiteLibrary.WidthRequest = 220;
		this.TurmiteLibrary.Name = "TurmiteLibrary";
		this.PropertiesPageLayout.Add(this.TurmiteLibrary);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.TurmiteLibrary]));
		w38.X = 13;
		w38.Y = 509;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.LabelTurmiteLibrary = new global::Gtk.Label();
		this.LabelTurmiteLibrary.Name = "LabelTurmiteLibrary";
		this.LabelTurmiteLibrary.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Turmite Library</b>");
		this.LabelTurmiteLibrary.UseMarkup = true;
		this.PropertiesPageLayout.Add(this.LabelTurmiteLibrary);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.LabelTurmiteLibrary]));
		w39.X = 13;
		w39.Y = 486;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'LibraryToolbar\'><toolitem name=\'CopyProgramButton\' action=\'Cop" +
				"yProgramButton\'/></toolbar></ui>");
		this.LibraryToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/LibraryToolbar")));
		this.LibraryToolbar.Name = "LibraryToolbar";
		this.LibraryToolbar.ShowArrow = false;
		this.PropertiesPageLayout.Add(this.LibraryToolbar);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.LibraryToolbar]));
		w40.X = 244;
		w40.Y = 504;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.AddButton = new global::Gtk.Button();
		this.AddButton.Name = "AddButton";
		this.AddButton.UseUnderline = true;
		this.AddButton.Label = global::Mono.Unix.Catalog.GetString("Add Turmite");
		this.PropertiesPageLayout.Add(this.AddButton);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.AddButton]));
		w41.X = 238;
		w41.Y = 442;
		// Container child PropertiesPageLayout.Gtk.Fixed+FixedChild
		this.Cyclic = new global::Gtk.CheckButton();
		this.Cyclic.Name = "Cyclic";
		this.Cyclic.Label = global::Mono.Unix.Catalog.GetString("Cyclic Boundary");
		this.Cyclic.DrawIndicator = true;
		this.Cyclic.UseUnderline = true;
		this.Cyclic.FocusOnClick = false;
		this.PropertiesPageLayout.Add(this.Cyclic);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.PropertiesPageLayout[this.Cyclic]));
		w42.X = 260;
		w42.Y = 392;
		this.PropertiesNotebook.Add(this.PropertiesPageLayout);
		// Notebook tab
		this.PropertiesPageLabel = new global::Gtk.Label();
		this.PropertiesPageLabel.Name = "PropertiesPageLabel";
		this.PropertiesPageLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Properties");
		this.PropertiesNotebook.SetTabLabel(this.PropertiesPageLayout, this.PropertiesPageLabel);
		this.PropertiesPageLabel.ShowAll();
		this.MainLayout.Add(this.PropertiesNotebook);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.PropertiesNotebook]));
		w44.X = 840;
		w44.Y = 60;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='MainToolbar'><toolitem name='RunButton' action='RunButton'/><toolitem name='PauseButton' action='PauseButton'/><toolitem name='SaveButton' action='SaveButton'/><toolitem name='ClearButton' action='ClearButton'/><toolitem name='ShowButton' action='ShowButton'/><separator/><toolitem name='QuitButton' action='QuitButton'/></toolbar></ui>");
		this.MainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MainToolbar")));
		this.MainToolbar.HeightRequest = 40;
		this.MainToolbar.Name = "MainToolbar";
		this.MainToolbar.ShowArrow = false;
		this.MainToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.MainToolbar.IconSize = ((global::Gtk.IconSize)(3));
		this.MainLayout.Add(this.MainToolbar);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainToolbar]));
		w45.X = 20;
		w45.Y = 10;
		this.Add(this.MainLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.QuitButton.Activated += new global::System.EventHandler(this.OnQuitButtonClicked);
		this.RunButton.Activated += new global::System.EventHandler(this.OnRunButtonClicked);
		this.PauseButton.Activated += new global::System.EventHandler(this.OnPauseButtonClicked);
		this.SaveButton.Activated += new global::System.EventHandler(this.OnSaveButtonClicked);
		this.ClearButton.Activated += new global::System.EventHandler(this.OnClearButtonClicked);
		this.ShowButton.Activated += new global::System.EventHandler(this.OnShowButtonClicked);
		this.CopyProgramButton.Activated += new global::System.EventHandler(this.OnCopyProgramButtonClicked);
		this.WorldEventBox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnWorldEventBoxButtonPressEvent);
		this.WorldEventBox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnWorldEventBoxButtonReleaseEvent);
		this.WorldEventBox.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler(this.OnWorldEventBoxMotionNotifyEvent);
		this.WorldImageScrollY.ValueChanged += new global::System.EventHandler(this.OnWorldImageScrollYValueChanged);
		this.WorldImageScrollX.ValueChanged += new global::System.EventHandler(this.OnWorldImageScrollXValueChanged);
		this.WorldWidth.ValueChanged += new global::System.EventHandler(this.OnWorldWidthValueChanged);
		this.WorldHeight.ValueChanged += new global::System.EventHandler(this.OnWorldHeightValueChanged);
		this.TurmitesList.Changed += new global::System.EventHandler(this.OnTurmitesListChanged);
		this.AddButton.Clicked += new global::System.EventHandler(this.OnAddButtonClicked);
	}
}
